/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.main.sendToServer;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Custommer;
import model.Order;
import model.User;

/**
 *
 * @author Binh Diep
 */
public class frmOrder extends javax.swing.JPanel {

    /**
     * Creates new form frmOrder
     */
    
    List<Order> listOrder = new ArrayList<>();
    sendToServer sts = new sendToServer();
    int sizeList = 0;
    User user;
    Order order;
    public frmOrder() {
        initComponents();
        setOpaque(false);
        loadForm();
    }
    public frmOrder (User user) {
        initComponents();
        setOpaque(false);
        this.user = user;
        loadForm();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCellAction1 = new com.raven.swing.table.TableCellAction();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.raven.swing.table.Table();
        btnCreate = new javax.swing.JButton();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Username", "Customer", "Date", "Total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 364, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    String getUserName(int UserId){
        String request = "GetUsername-Account-"+UserId;
        User user = (User) sts.Action(request);
        return user.getUsername();
    }
    
    Custommer getCustommer(int CustommerId){
        String request = "GetCustommer-Custommer-"+CustommerId;
        Custommer model = (Custommer) sts.Action(request);
        return model;
    }
    
    public void loadForm(){
        String request = "GetAll-Order";
        List<Order> listData = (List<Order>) sts.Action(request);
        bingdingTable(listData);
    }
    
    public void bingdingTable( List<Order> listData){
        DefaultTableModel tblModel = (DefaultTableModel)table1.getModel();
        DecimalFormat decimalFormat = new DecimalFormat("#,##0.00");
        while(tblModel.getRowCount() > 0)
        {
            tblModel.removeRow(0);
        }
        if (listData != null) {
            for (Order order : listData) {
                String username = getUserName(order.getUserId());
                String custommerName = getCustommer(order.getCustomerId()).getCustomerName();
                
                String tbData[] = { String.valueOf(order.getId()), username,
                    custommerName,order.getDate().toString(),String.valueOf(decimalFormat.format( order.getTotalAmount())),order.getStatus()};
                tblModel.addRow(tbData);
            }
        }
    }
    
    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int index = table1.getSelectedRow();
        TableModel model = table1.getModel();
        int orderId = Integer.parseInt( model.getValueAt(index,0).toString());
        String request = "GetOrder-Order-"+orderId;
        this.order = (Order) sts.Action(request);
        System.out.println(this.order.getCustomerId());
        new frmOrderDetails(this.order).setVisible(true);
        
    }//GEN-LAST:event_table1MouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String request = "Create-Order";
        Order order = (Order) sts.Action(request);
        new frmOrderDetails(order).setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.table.Table table1;
    private com.raven.swing.table.TableCellAction tableCellAction1;
    // End of variables declaration//GEN-END:variables
}
